version: "3"

services:
  axon-server:
    image: axoniq/axonserver:4.6.4
    container_name: axon-server
    healthcheck:
      test: curl -f http://localhost:8024/actuator/health || exit 1;
    ports:
      - 8024:8024
      - 8124:8124